import Head from "next/head";
import React, { ReactNode } from "react";
import FooterComponent from "../FooterComponent";

interface props {
  children: ReactNode;
  headTitle?: string;
}

const DefaultLayout: React.FC<props> = ({
  children,
  headTitle = "no title page",
}) => {
  return (
    <div className="">
      <Head>
        <title>{headTitle}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {children}
      <FooterComponent />
    </div>
  );
};

export default DefaultLayout;
